#!/usr/bin/env bash

# Bash script that connects to a webserver

# Credentials
ssh_key="~/.ssh/school"
username="ubuntu"
host_ip="54.90.46.184"

# Connections
ssh -i "$ssh_key" "$username"@"$host_ip"
