#!/usr/bin/env bash

# This script prints 1 to 20 with special message

#Initialize a variable
counter=1

# Use While Loop to iterate from 1 to 20
while [ $counter -le 20 ]; do
	case $counter in
	4)
		echo "$counter"
		echo "bad luck from China"
		;;
	9)
		echo "$counter"
		echo "bad luck from Japan"
		;;
	17)
		echo "$counter"
		echo "bad luck from Italy"
		;;
	*)
		echo "$counter"
		;;
	esac

	((counter++))
done
